author: Chris Zuber
title: "Piazza's Pine Cone Inn"
shortName: Pine Cone Inn
# url: ''
markdown: kramdown
version: 1.0.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: width=device-width
robots: 'follow, index'
referrer: origin-when-cross-origin
manifest: /manifest.json
tiles-config: /browserconfig.xml
# service_worker:
og-type: website
description: "Family owned and operated since 1955 in Kernville, CA."
mobile-web-app-capable: true
# canonical: ''
keywords:
- hotel
- motel
- inn
- Piazza
- Pine Cone
- Kernville
- Kern Valley
- Kern River Valley
- Lake Isabella
repository:
  username: shgysk8zer0
  project: pine-cone
  title: Pine Cone Inn
# twitter:
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: '/img/icons.svg'
theme-color: '#c12026'
background-color: '#242424'
# discus-identifier:
# google-analytics:
# ad-sense:
# webmaster-verifications:
#   google:
#   bing:
scripts:
  development:
  - src: /js/index.js
    async: true
  - src: 'https://cdn.kernvalley.us/components/share-button.js'
    type: module
    async: true
    crossorigin: anonymous
  - src: 'https://cdn.kernvalley.us/components/leaflet/map.js'
    type: module
    async: true
    crossorigin: anonymous
  - src: 'https://cdn.kernvalley.us/components/leaflet/marker.js'
    type: module
    async: true
    crossorigin: anonymous
  production:
  - src: 'https://cdn.polyfill.io/v3/polyfill.min.js'
    type: text/javascript
    crossorigin: anonymous
  - src: 'https://unpkg.com/@webcomponents/custom-elements@1.3.2/custom-elements.min.js'
    crossorigin: anonymous
    integrity: sha384-d4ryOI4Ng+/P1p3ZWsXqWquUYtNHWo9FMxDmDCQhnvogfIzbSz5DoBDfpmqAEBnV
  - src: /js/index.min.js
    async: true
  - src: 'https://cdn.kernvalley.us/components/share-button.js'
    type: module
    async: true
    crossorigin: anonymous
  - src: 'https://cdn.kernvalley.us/components/leaflet/map.js'
    type: module
    async: true
    crossorigin: anonymous
  - src: 'https://cdn.kernvalley.us/components/leaflet/marker.js'
    type: module
    async: true
    crossorigin: anonymous
stylesheets:
  development:
  - href: /css/index.css
    media: all
  production:
  - href: /css/index.min.css
    media: all
preload:
- href: /img/icons.svg
  as: image
  type: image/svg+xml
appicons:
- src: /img/favicon.svg
  sizes: any
  type: image/svg+xml
- src: /img/icon-512.png
  sizes: 512x512
  type: image/png
- src: /img/icon-192.png
  sizes: 192x192
  type: image/png
screenshots:
- src: 'https://i.imgur.com/uRKaQQQl.png'
  sizes: 640x354
  type: image/png
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: shgysk8zer0
      twitter: shgysk8zer0
      linkedin: chris-zuber-455346141/
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: 'shgysk8zer0'
      twitter: shgysk8zer0
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
              url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: false
    ads: false
plugins:
- jekyll-gist
- jekyll-youtube
- jekyll-admin
- jekyll-watch
- jekyll-paginate
exclude:
- ".gitkeep"
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "*.config.js"
- ".gitkeep"
- docs/
- "/.github/"
- Gemfile
- node_modules/
- palette.xml
- README.md
- LICENSE
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
